// AUTO-CURATED — this file is the source of truth for the deny list.
// Edit terms here; the surrounding moderation pipeline auto-loads at
// module init. Curator-facing structure (sections + REVIEW notes) lives
// in this same file so future edits stay coherent.
//
// Curation rule:
//   KEEP — sexual-explicit terms (paraphilias, sex acts, sex toys, adult
//          brands), slurs (ethnic, racial, anti-LGBTQ, ableist,
//          anti-Jewish, religious), illegal-content references
//          (CSAM-adjacent, violence-instructional), hate-symbol refs.
//   DROP — mild swears (fuck/shit/damn/hell/crap/piss/ass tier),
//          standalone clinical anatomy (anus, penis, vagina, rectum,
//          vulva, nipple, fecal, semen, genitals), common-word
//          substrings prone to false positives (sex, scat, swinger,
//          escort, snatch, hardcore, kinky, etc.).
//
// Source: filtered subset of LDNOOBW (Shutterstock-maintained, MIT) +
// additions in slur categories LDNOOBW under-covers (anti-Asian,
// ableist, anti-Jewish, anti-Indigenous), plus common plurals.
//
// Counts (by primary category — many overlap):
//   Sexual-explicit:                  231
//   Slurs (ethnic / racial):           41
//   Slurs (anti-LGBTQ):                12
//   Slurs (ableist):                    5
//   Slurs (gendered, strong tier):      2
//   Hate symbols / hate-group refs:     3
//   Illegal-content / violence:        20
//   Total:                            314
//
// REVIEW notes — judgment calls to sanity-check:
//   Dropped you may want kept: bitch (per allow-basic-swears),
//     dick (false positives on given name), hooker (sex-work slur but
//     fishing/surname false positives).
//   Kept you may want dropped: cunt (American: strong slur), negro,
//     lolita (Nabokov title), poof (UK slur + onomatopoeia), shibari,
//     twink (sometimes reclaimed), jap, redskin, tit (matches
//     "tit for tat"), heeb/yid, horny/boner/busty.
//
// The matched term is NEVER returned in API responses or logs — only
// an HMAC hash (denylist_term_hash) operators can resolve locally.

export const BLOCKED_TERMS: readonly string[] = [
  // === Sexual-explicit (paraphilias, sex acts, sex toys, adult-content brands) ===
  "2g1c",
  "2 girls 1 cup",
  "acrotomophilia",
  "alabama hot pocket",
  "alaskan pipeline",
  "anal",
  "anilingus",
  "auto erotic",
  "autoerotic",
  "babeland",
  "baby batter",
  "baby juice",
  "ball gag",
  "ball gravy",
  "ball kicking",
  "ball licking",
  "ball sucking",
  "bangbros",
  "bangbus",
  "bareback",
  "bastinado",
  "bbw",
  "bdsm",
  "beaver cleaver",
  "beaver lips",
  "beastiality",
  "bestiality",
  "big breasts",
  "big knockers",
  "big tits",
  "birdlock",
  "black cock",
  "blonde action",
  "blonde on blonde action",
  "blowjob",
  "blow job",
  "blow your load",
  "blue waffle",
  "blumpkin",
  "bondage",
  "boner",
  "booty call",
  "brown showers",
  "brunette action",
  "bukkake",
  "bullet vibe",
  "busty",
  "camel toe",
  "camgirl",
  "camslut",
  "camwhore",
  "chocolate rosebuds",
  "circlejerk",
  "cleveland steamer",
  "clit",
  "clover clamps",
  "cock",
  "cocks",
  "coprolagnia",
  "coprophilia",
  "creampie",
  "cum",
  "cumming",
  "cumshot",
  "cumshots",
  "cunnilingus",
  "deep throat",
  "deepthroat",
  "dendrophilia",
  "dildo",
  "dingleberry",
  "dingleberries",
  "dirty pillows",
  "dirty sanchez",
  "doggie style",
  "doggiestyle",
  "doggy style",
  "doggystyle",
  "dog style",
  "dolcett",
  "dominatrix",
  "dommes",
  "donkey punch",
  "double dong",
  "double penetration",
  "dp action",
  "dry hump",
  "dvda",
  "ecchi",
  "ejaculation",
  "erotic",
  "erotism",
  "felch",
  "feltch",
  "fellatio",
  "female squirting",
  "femdom",
  "figging",
  "fingerbang",
  "fingering",
  "fisting",
  "foot fetish",
  "footjob",
  "frotting",
  "fudge packer",
  "fudgepacker",
  "futanari",
  "gangbang",
  "gang bang",
  "gay sex",
  "giant cock",
  "girls gone wild",
  "goatcx",
  "goatse",
  "gokkun",
  "golden shower",
  "goo girl",
  "goregasm",
  "group sex",
  "guro",
  "hand job",
  "handjob",
  "hentai",
  "homoerotic",
  "horny",
  "hot carl",
  "humping",
  "jack off",
  "jerk off",
  "jizz",
  "juggs",
  "kinbaku",
  "knobbing",
  "lemon party",
  "livesex",
  "male squirting",
  "masturbate",
  "masturbating",
  "masturbation",
  "menage a trois",
  "milf",
  "missionary position",
  "mound of venus",
  "mr hands",
  "muff diver",
  "muffdiving",
  "nawashi",
  "nimphomania",
  "nutten",
  "nympho",
  "nymphomania",
  "omorashi",
  "one cup two girls",
  "one guy one jar",
  "orgasm",
  "orgy",
  "pegging",
  "phone sex",
  "piss pig",
  "pisspig",
  "pleasure chest",
  "ponyplay",
  "poon",
  "poontang",
  "punany",
  "poop chute",
  "poopchute",
  "porn",
  "porno",
  "pornography",
  "pussy",
  "quim",
  "raging boner",
  "reverse cowgirl",
  "rimjob",
  "rosy palm",
  "rosy palm and her 5 sisters",
  "rusty trombone",
  "schlong",
  "scissoring",
  "sexcam",
  "sexo",
  "shaved beaver",
  "shaved pussy",
  "shibari",
  "slut",
  "s&m",
  "smut",
  "sodomize",
  "sodomy",
  "splooge",
  "splooge moose",
  "spooge",
  "strap on",
  "strapon",
  "strappado",
  "strip club",
  "style doggy",
  "suicide girls",
  "tea bagging",
  "threesome",
  "throating",
  "thumbzilla",
  "tit",
  "tits",
  "titties",
  "titty",
  "tribadism",
  "tub girl",
  "tubgirl",
  "twat",
  "twink",
  "two girls one cup",
  "urethra play",
  "urophilia",
  "venus mound",
  "violet wand",
  "vorarephilia",
  "voyeur",
  "voyeurweb",
  "voyuer",
  "wank",
  "wet dream",
  "whore",
  "worldsex",
  "wrapping men",
  "wrinkled starfish",
  "xxx",
  "yaoi",
  "yellow showers",
  "yiffy",

  // === Slurs — ethnic / racial ===
  "beaner",
  "beaners",
  "chink",
  "chinks",
  "coon",
  "coons",
  "darkie",
  "darkies",
  "gook",
  "gooks",
  "heeb",
  "honkey",
  "injun",
  "jap",
  "japs",
  "jigaboo",
  "jiggaboo",
  "jiggerboo",
  "jigaboos",
  "kike",
  "kikes",
  "negro",
  "nigga",
  "niggas",
  "nigger",
  "niggers",
  "nig nog",
  "paki",
  "pakis",
  "pikey",
  "raghead",
  "ragheads",
  "redskin",
  "slanteye",
  "spic",
  "spics",
  "towelhead",
  "towelheads",
  "wetback",
  "wetbacks",
  "yid",

  // === Slurs — anti-LGBTQ ===
  "bulldyke",
  "carpet muncher",
  "carpetmuncher",
  "fag",
  "fags",
  "faggot",
  "faggots",
  "pole smoker",
  "poof",
  "shemale",
  "tranny",
  "trannies",

  // === Slurs — ableist ===
  "mong",
  "retard",
  "retarded",
  "spastic",
  "spaz",

  // === Slurs — gendered (stronger end) ===
  "cunt",
  "cunts",

  // === Hate symbols / hate-group references ===
  "neonazi",
  "swastika",
  "white power",

  // === Illegal-content / CSAM-adjacent / violence-instructional ===
  "barely legal",
  "date rape",
  "daterape",
  "how to kill",
  "how to murder",
  "incest",
  "jail bait",
  "jailbait",
  "lolita",
  "nambla",
  "paedophile",
  "pedobear",
  "pedophile",
  "pthc",
  "rape",
  "raping",
  "rapist",
  "shota",
  "upskirt",
  "zoophilia",
];
